name: David Heurtel-Depeiges
description: Personal website
menu:

 #- page: About
 #  url: /about
 #- page: Papers
  # url: /papers
   #links:
    #- title: Working papers
     # url: "#working-papers"
    #- title: Published papers
     # url: "#published-papers"
 #- page: Research Projects
 #  url: /research
  # links:
   # - title: "Project One"
    #  url: "#project-one"
    #- title: "Project Two"
     # url: "#project-two"
 - page: Papers
  url : /papers
 - page: Curriculum Vitae
   url: "Heurtel-Depeiges_ResumeC.pdf"
 - page: License
   url: /license
  - page: Outside of work 
   url: /misc
#menu_external:
 #- title: OleVik.me
  # url: "http://olevik.me/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: david.heurtel-depeiges.github.io
